version: '3.8'

services:
  backend:
    build: .
    container_name: erp_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env

  frontend:
    build: .
    container_name: erp_frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:            
      - .env
    depends_on:
      - backend
    # ADD THIS LINE
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0